# Generated by Django 3.1.4 on 2021-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='subtitle')),
                ('background', models.ImageField(upload_to='site/slideshow', verbose_name='background')),
                ('action_text', models.CharField(max_length=50, verbose_name='action text')),
                ('action_url', models.URLField(default='http://127.0.0.1:8000', verbose_name='action url')),
            ],
        ),
    ]
