# Generated by Django 3.1.4 on 2021-01-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name': 'SlideShow', 'verbose_name_plural': 'SlideShows'},
        ),
    ]
