# Generated by Django 3.1.4 on 2021-02-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0003_advertisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='AdvertisementSide',
        ),
    ]
