# Generated by Django 3.1.4 on 2021-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0004_auto_20210217_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.ImageField(max_length=50, upload_to='', verbose_name='section1')),
                ('section2', models.ImageField(max_length=50, upload_to='', verbose_name='section2')),
                ('section3', models.ImageField(max_length=50, upload_to='', verbose_name='section3')),
                ('section4', models.ImageField(max_length=50, upload_to='', verbose_name='section4')),
                ('section5', models.ImageField(max_length=50, upload_to='', verbose_name='section5')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
