# Generated by Django 3.1.4 on 2021-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0006_auto_20210217_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementside',
            name='background',
        ),
        migrations.AddField(
            model_name='advertisementside',
            name='image',
            field=models.ImageField(default='/media/site/advertizement/addd.jpg', upload_to='site/Advertisement', verbose_name='image'),
            preserve_default=False,
        ),
    ]
