# Generated by Django 3.1.4 on 2020-12-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avator',
            field=models.ImageField(null=True, upload_to='users/avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(null=True, verbose_name='Mobile_number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone_number'),
        ),
    ]
