# Generated by Django 3.1.4 on 2021-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discreption',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
