# Generated by Django 3.1.4 on 2021-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210117_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avator',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
