# Generated by Django 3.1.4 on 2021-02-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210121_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='09', null=True, verbose_name='Mobile_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, default='021', null=True, verbose_name='Phone_number'),
        ),
    ]
