# Generated by Django 3.1.4 on 2021-01-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210117_1347'),
        ('orders', '0002_remove_basketitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='orders.basket', verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='basketitems',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product', to='products.shopproduct', verbose_name='Shop_product'),
        ),
    ]
