# Generated by Django 3.1.4 on 2021-01-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210117_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitems',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
