# Generated by Django 3.1.4 on 2021-01-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210122_0128'),
        ('orders', '0004_basketitems_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitems',
            unique_together={('basket', 'shop_product')},
        ),
    ]
