# Generated by Django 3.1.4 on 2021-02-12 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210122_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update_at'),
        ),
    ]
