# Generated by Django 3.1.4 on 2021-02-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210214_1535'),
        ('orders', '0008_payment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopproduct', to='products.shopproduct', verbose_name='Shop_product_orderItems'),
        ),
    ]
