# Generated by Django 3.1.4 on 2021-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210122_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
    ]
