# Generated by Django 3.1.4 on 2021-02-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_favorite', to='products.shopproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'shop_product')},
        ),
    ]
