# Generated by Django 3.1.4 on 2021-02-02 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210202_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='products.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at'),
        ),
    ]
