# Generated by Django 3.1.4 on 2021-02-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210209_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'CategoryMeta',
                'verbose_name_plural': 'CategoryMetas',
            },
        ),
        migrations.CreateModel(
            name='CategoryMetaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Label')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorymeta', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'CategoryMetaValue',
                'verbose_name_plural': 'CategoryMetaValues',
            },
        ),
    ]
