# Generated by Django 3.1.4 on 2021-02-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_categorymeta_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymeta',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_meta', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorymetavalue',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_category_meta', to='products.categorymeta', verbose_name='Product'),
        ),
    ]
