# Generated by Django 3.1.4 on 2021-02-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210214_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymetavalue',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_meta', to='products.categorymeta', verbose_name='Product'),
        ),
    ]
