# Generated by Django 3.1.4 on 2021-02-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210217_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymetavalue',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_meta', to='products.categorymeta', verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='categorymetavalue',
            name='value',
            field=models.CharField(max_length=50, verbose_name='value'),
        ),
    ]
